#!/bin/sh

fresh freshshell/fresh bin/fresh --bin
fresh freshshell/fresh contrib/source-build.sh --file=~/.zshrc

fresh config/\*

# Bin scripts
fresh bin/\* --bin

# Git
fresh-options --file=~/.gitconfig --marker
  fresh git/\*
fresh-options

# Oh my zsh
fresh robbyrussell/oh-my-zsh . --file=~/.config/oh-my-zsh/
fresh zsh/kizza.zsh-theme --file=~/.config/oh-my-zsh-custom/themes/kizza.zsh-theme

# Syntax highlighting
fresh zsh-users/zsh-syntax-highlighting . --file=~/.config/oh-my-zsh-custom/plugins/zsh-syntax-highlighting/
fresh zsh-users/zsh-completions . --file=~/.config/oh-my-zsh-custom/plugins/zsh-completions/
fresh zsh-users/zsh-history-substring-search . --file=~/.config/oh-my-zsh-custom/plugins/zsh-history-substring-search/

# Base 16
fresh chriskempson/base16-shell . --file=~/.config/base16-shell/
fresh config/base-16.sh

# tmux-up
fresh jamesottaway/tmux-up tmux-up --bin

# Vim
fresh vim/begin.vim --file=~/.vimrc
fresh-options --file=~/.vimrc
  fresh vim/plugins/\*.vim
fresh-options
fresh vim/end.vim --file=~/.vimrc
fresh vim/config/\*.vim --file=~/.vimrc

# Coc config
fresh vim/misc/coc-settings.json --file=~/.config/nvim/coc-settings.json
fresh vim/misc/coc-settings.json --file=~/.vim/coc-settings.json

# Syntax
fresh vim/syntax/nerdtree.vim --file=~/.vim/syntax/nerdtree.vim
fresh vim/syntax/gitcommit.vim --file=~/.vim/syntax/gitcommit.vim
fresh vim/syntax/typescript.vim --file=~/.vim/syntax/typescript.vim

# Alacritty
fresh alacritty/alacritty.yml --file="~/.config/alacritty/alacritty.yml"

# Vscode
fresh vscode/keybindings.json --file="~/Library/Application Support/Code/User/keybindings.json"

# Snippets
fresh vim/snippets/javascript.snippets --file=~/.vim/snippets/javascript.snippets
fresh vim/snippets/python.snippets --file=~/.vim/snippets/python.snippets
fresh vim/snippets/ruby.snippets --file=~/.vim/snippets/ruby.snippets
fresh vim/snippets/typescript.snippets --file=~/.vim/snippets/typescript.snippets
fresh vim/snippets/elixir.snippets --file=~/.vim/snippets/elixir.snippets
