#!/bin/sh

fresh freshshell/fresh bin/fresh --bin
fresh freshshell/fresh contrib/source-build.sh --file=~/.zshrc

fresh config/\*

# Git
fresh-options --file=~/.gitconfig --marker
  fresh git/config
  fresh git/alias
fresh-options

# Oh my zsh
fresh robbyrussell/oh-my-zsh . --file=~/.config/oh-my-zsh/

# Base 16
fresh chriskempson/base16-shell . --file=~/.config/base16-shell/
fresh config/base-16.sh

# tmux-up
fresh jamesottaway/tmux-up tmux-up --bin

# Vim
fresh vim/begin.vim --file=~/.vimrc
fresh-options --file=~/.vimrc
  fresh vim/plugins/\*.vim
fresh-options
fresh vim/end.vim --file=~/.vimrc
fresh vim/config/\*.vim --file=~/.vimrc

# Alacritty
fresh alacritty/alacritty.yml --file="~/.config/alacritty/alacritty.yml"

# Vscode
fresh vscode/keybindings.json --file="~/Library/Application Support/Code/User/keybindings.json"

# Snippets
fresh vim/snippets/javascript.snippets --file=~/.vim/snippets/javascript.snippets
fresh vim/snippets/python.snippets --file=~/.vim/snippets/python.snippets
fresh vim/snippets/ruby.snippets --file=~/.vim/snippets/ruby.snippets
fresh vim/snippets/typescript.snippets --file=~/.vim/snippets/typescript.snippets
fresh vim/snippets/elixir.snippets --file=~/.vim/snippets/elixir.snippets
